#!/usr/bin/env python3
"""Render the survey markdown (literature/survey/*.md) to printable, math-typeset HTML.

Why this exists: the survey docs are heavy on LaTeX math ($...$ / $$...$$). A plain
markdown->HTML pass mangles LaTeX (Markdown reads `_`/`*` inside math as emphasis), so
we protect every math span behind an inert placeholder, run Markdown, then restore the
raw math and let MathJax typeset it in the browser.

Output is intentionally NOT committed to the repo — it would drift out of sync with the
.md source. Regenerate on demand; the .md files are the single source of truth.

Usage:
    python3 scripts/render_survey_html.py [OUTPUT_DIR]
    (OUTPUT_DIR defaults to <tmp>/survey-html)

Requires the `markdown` package:  pip install markdown
Note: the generated HTML pulls MathJax from a CDN, so viewing it needs network access
the first time (styling is inlined and self-contained).
"""
import os, re, sys, html, tempfile

try:
    import markdown
except ImportError:
    sys.exit("Missing dependency: pip install markdown  (ideally into a venv)")

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, "literature", "survey")
OUT = sys.argv[1] if len(sys.argv) > 1 else os.path.join(tempfile.gettempdir(), "survey-html")

# --- math protection: bare alphanumeric token, NO surrounding spaces ---------------
# (Markdown strips block-leading/table-edge whitespace; a space-padded token would then
#  fail to restore. A bare token survives verbatim.)
def _tok(i):
    return "MJXZ" + str(i) + "ZMJX"

def protect_math(text):
    store = []
    def stash(m):
        store.append(m.group(0))
        return _tok(len(store) - 1)
    text = re.sub(r"\$\$.+?\$\$", stash, text, flags=re.DOTALL)  # display first
    text = re.sub(r"\$[^\$\n]+?\$", stash, text)                 # then inline
    return text, store

def restore_math(htmltext, store):
    for i, raw in enumerate(store):
        htmltext = htmltext.replace(_tok(i), raw)
    return htmltext

CSS = """
@page { size: Letter; margin: 1in 0.9in; }
html { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
body { font-family: Georgia, 'Times New Roman', serif; font-size: 10.5pt; line-height: 1.45; color: #111; }
h1 { font-size: 19pt; border-bottom: 2px solid #333; padding-bottom: 4px; }
h2 { font-size: 15pt; margin-top: 1.4em; border-bottom: 1px solid #bbb; padding-bottom: 2px; }
h3 { font-size: 12.5pt; margin-top: 1.2em; }
h4 { font-size: 11pt; }
h1,h2,h3,h4 { font-family: 'Helvetica Neue', Arial, sans-serif; line-height: 1.2; }
code { font-family: 'SF Mono','Menlo',monospace; font-size: 0.86em; background:#f3f3f3; padding: 0.5px 3px; border-radius: 3px; }
pre { background:#f6f6f6; padding: 8px 10px; border-radius:5px; overflow-x:auto; font-size:0.82em; }
a { color: #1a7f4b; text-decoration: none; }
blockquote { border-left: 3px solid #cdb; background:#fafdf8; margin: 0.8em 0; padding: 2px 14px; }
table { border-collapse: collapse; font-size: 8.6pt; margin: 0.8em 0; width:100%; }
th,td { border: 1px solid #bbb; padding: 3px 6px; vertical-align: top; text-align:left; }
th { background:#eee; }
hr { border: none; border-top: 1px solid #ccc; margin: 1.4em 0; }
.docheader { color:#666; font-family:'Helvetica Neue',Arial,sans-serif; font-size:8.5pt; border-bottom:1px solid #ccc; padding-bottom:3px; margin-bottom:1.2em; }
mjx-container[display="true"] { overflow-x: auto; overflow-y: hidden; }
"""

HEAD = """<!doctype html><html><head><meta charset="utf-8">
<title>%(title)s</title>
<script>
window.MathJax = { tex: { inlineMath: [['$','$']], displayMath: [['$$','$$']], processEscapes: true },
  options: { skipHtmlTags: ['script','noscript','style','textarea','pre','code'] } };
</script>
<script async src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml.js"></script>
<style>%(css)s</style></head><body>
<div class="docheader">%(title)s &middot; literature/survey &middot; generated by scripts/render_survey_html.py</div>
"""

def main():
    os.makedirs(OUT, exist_ok=True)
    md_files = sorted(f for f in os.listdir(SRC) if f.endswith(".md"))
    if not md_files:
        sys.exit("No .md files found in " + SRC)
    rc = 0
    for fn in md_files:
        raw = open(os.path.join(SRC, fn)).read()
        protected, store = protect_math(raw)
        body = markdown.markdown(protected, extensions=["tables", "fenced_code", "sane_lists", "attr_list"])
        body = restore_math(body, store)
        page = (HEAD % {"title": html.escape(fn), "css": CSS}) + body + "</body></html>"
        leftover = len(re.findall(r"MJXZ\d+ZMJX", page))
        out_path = os.path.join(OUT, fn[:-3] + ".html")
        with open(out_path, "w") as fh:
            fh.write(page)
        status = "OK" if leftover == 0 else ("!!! %d UNRESTORED math placeholders" % leftover)
        if leftover:
            rc = 1
        print("%s  (%d math spans)  %s  -> %s" % (fn, len(store), status, out_path))
    sys.exit(rc)

if __name__ == "__main__":
    main()
